### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by 8188** [vivishow/liangongbao#1]
win10环境 执行mitmdump出错
ImportError: DLL load failed while importing _openssl: 找不到指定的模块。

**Comment by vivishow** [comment]
> 

python是什么版本？

**Comment by 8188** [comment]
3.9.7
D:\文档\Python\liangongbao>mitmdump -s aqy.py -p 8888 "~d h5we.lgb360.com"
Traceback (most recent call last):
  File "e:\Miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\Miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Miniconda3\Scripts\mitmdump.exe\__main__.py", line 4, in <module>
  File "e:\Miniconda3\lib\site-packages\mitmproxy\tools\main.py", line 9, in <module>
    from mitmproxy import exceptions, master
  File "e:\Miniconda3\lib\site-packages\mitmproxy\master.py", line 5, in <module>
    from mitmproxy import addonmanager, hooks
  File "e:\Miniconda3\lib\site-packages\mitmproxy\addonmanager.py", line 11, in <module>
    from mitmproxy import hooks
  File "e:\Miniconda3\lib\site-packages\mitmproxy\hooks.py", line 7, in <module>
    import mitmproxy.flow
  File "e:\Miniconda3\lib\site-packages\mitmproxy\flow.py", line 6, in <module>
    from mitmproxy import connection
  File "e:\Miniconda3\lib\site-packages\mitmproxy\connection.py", line 8, in <module>
    from mitmproxy import certs
  File "e:\Miniconda3\lib\site-packages\mitmproxy\certs.py", line 17, in <module>
    import OpenSSL
  File "e:\Miniconda3\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "e:\Miniconda3\lib\site-packages\OpenSSL\crypto.py", line 17, in <module>
    from OpenSSL._util import (
  File "e:\Miniconda3\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "e:\Miniconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed while importing _openssl: 找不到指定的模块。

**Comment by vivishow** [comment]
https://www.python.org/downloads/ 在这里下一个，miniconda可能没有加入环境变量

**Comment by 8188** [comment]
我下载mitmproxy.exe安装可以了，谢谢

**Comment by vivishow** [comment]
按照这个试一下添加环境变量

打开任意一个文件夹，将鼠标放在 “此电脑” 上- 右键-点击“属性” → 点击“高级系统设置” → “环境变量” → 系统变量中的 “Path” → 添加路径（…\Miniconda3\Library\bin）
注意：若之前 …\Miniconda3 和 …\Miniconda3\Scripts 没有添加到Path中，也需要将其添加

**Comment by vivishow** [comment]
好的，感谢你又提供了一种方法。
