### ISSUE TITLE
I can't run mitmdump in a conda env

### ISSUE THREAD

**Issue by Cigerant** [vivishow/liangongbao#11]
I build a conda python env by the following command:

`conda create --name liangongbao python=3.8`

And then, I install the mitmdump package:

`python -m pip install --upgrade pip`
`pip install mitmproxy`

After finishing install the python package, I switch to the projects directory, and run the command in README.md

`mitmdump -s aqy.py -p 8888 -q`

However, I encountered the following error:

> Traceback (most recent call last):
  File "C:\Users\xxx\.conda\envs\script_test\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xxx\.conda\envs\script_test\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\.conda\envs\script_test\Scripts\mitmdump.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\.conda\envs\script_test\lib\site-packages\mitmproxy\tools\main.py", line 137, in mitmdump
    from mitmproxy.tools import dump
  File "C:\Users\xxx\.conda\envs\script_test\lib\site-packages\mitmproxy\tools\dump.py", line 1, in <module>
    from mitmproxy import addons
  File "C:\Users\xxx\.conda\envs\script_test\lib\site-packages\mitmproxy\addons\__init__.py", line 14, in <module>
    from mitmproxy.addons import onboarding
  File "C:\Users\xxx\.conda\envs\script_test\lib\site-packages\mitmproxy\addons\onboarding.py", line 2, in <module>
    from mitmproxy.addons.onboardingapp import app
  File "C:\Users\xxx\.conda\envs\script_test\lib\site-packages\mitmproxy\addons\onboardingapp\__init__.py", line 3, in <module>
    from flask import Flask, render_template
  File "C:\Users\xxx\.conda\envs\script_test\lib\site-packages\flask\__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "C:\Users\xxx\.conda\envs\script_test\lib\site-packages\flask\app.py", line 28, in <module>
    from . import cli
  File "C:\Users\xxx\.conda\envs\script_test\lib\site-packages\flask\cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "C:\Users\xxx\.conda\envs\script_test\lib\site-packages\flask\helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (C:\Users\xxx\.conda\envs\script_test\lib\site-packages\werkzeug\urls.py)

So, how can I solve the problem?
Thanks for any answers!!!

**Comment by vivishow** [comment]
Try from https://mitmproxy.org/   download mitmproxy and install it

**Comment by Cigerant** [comment]
Thank you for your answer! I create a new conda env which python version is 3.11and use the `.whl` file downloaded from [https://mitmproxy.org/](url) , now I can run the service normally!
